app_code: bk_xxx
app_name: xx平台
app_name_en: BK XXX
is_use_celery: True
author: 蓝鲸智云
introduction: 中文描述
introduction_en: 英文描述
version: 1.0.0
category: 运维工具
desktop:
  width: 1300
  height: 720
  is_max: True
container:
    memory: 4096
env:
    - key: BKAPP_ENABLE_SHARED_FS
      value: "1"